### ISSUE TITLE
Shrinkpack as solution to NPM-Left-Pad-Gate?

### ISSUE THREAD

**Issue by markerikson** [JamieMason/shrinkpack#16]
It seems to me that Shrinkpack solves many of the issues involved with the whole transitive dependencies problem, by ensuring that you have local copies rather than always pulling down files from NPM's servers.  I've found myself posting links to this tool in a number of discussion threads, sort of trying to raise awareness a bit.

Maybe worth making a concerted effort to try to advertise Shrinkpack?  I'm still very surprised more people haven't started using this tool.

**Comment by JamieMason** [comment]
Thanks very much for this @markerikson, I've noticed some of your comments mentioning shrinkpack and am hugely grateful that you took the time to do that.

I've tried putting the word out (mostly on Twitter) but have found it very difficult to get any traction. It's totally understandable though. Let's be honest, Shrinkpack is part of some of the more boring aspects of Development. 

It's also a problem that a only subset of Developers are likely to be concerned about, those in large teams that release regularly, and that are maybe running somewhat important projects.

That said, I'm totally fine with this — I open source things that I find useful and use in my work. If other people use it, that's really great and a nice bonus.

Thanks again for spreading the word,

Jamie

**Comment by markerikson** [comment]
Sure.  For what it's worth, I do think it's useful for more than _just_ "large teams that release regularly".  For _really_ large teams, I could see the value of running an internal NPM server or something, or if you have a bunch of related projects.  But, for a lot of other situations, Shrinkpack seems to nail the use case.

I'll freely admit that I have not yet used it in a meaningful production situation.  I started doing research on the NPM/React/Redux ecosystem last year, have spent the last couple months working on and off on a prototype, but we don't have full approval to work on it yet.  Still, the usage seems very straightforward and the benefits are real.

I'll keep mentioning it in discussion threads and stuff when I get a chance.  Thanks for making a very useful tool!

**Comment by JamieMason** [comment]
Thanks @markerikson. I totally agree and would urge anyone developing a project to use either shrinkpack or a caching proxy or mirror to help protect themselves from regressions and takedowns. 

What I meant to say was that, although I believe this is something people should do, that subset of Developers are the only group I think _might_ pay it some attention. I just don't think diligent practices like these are particularly well known or cared about in the JavaScript community [citation needed] yet, like they are in some of the more mature languages.

I wouldn't recommend shrinkpack if you're developing an npm package by the way, only for projects which are the top of the tree of dependencies, like a web app, blog, or some other product etc.

Hopefully these kinds of practices will catch on, and not because of another #unpublishgate :)
