### ISSUE TITLE
npm install some-shrinkpacked-package

### ISSUE THREAD

**Issue by aju** [JamieMason/shrinkpack#56]
#### Expected behaviour

Installing shrinkpacked module as dev dependency
...
#### Actual behaviour

Throws erros like: `ENOENT: no such file or directory, open '/Users/anmaciur/Projects/kkk/node_modules/style-guide/node_shrinkwrap/abbrev-1.0.9.tgz'`
...
#### Steps to reproduce

Hi I have a project https://github.com/brainly/style-guide/tree/v44.0.1
that I want to install as dependency. Running command:
`npm i git+https://github.com/brainly/style-guide.git#v44.0.1`
throws erros like: 
`ENOENT: no such file or directory, open '/Users/anmaciur/Projects/kkk/node_modules/style-guide/node_shrinkwrap/abbrev-1.0.9.tgz'`
...
#### Software versions used

```
OS         :  OSX
node.js    :  6.2.2
npm        : 3.10.4 (I tried on older versions as well 3.8.0)
shrinkpack : 0.13.1
```
#### Contents of your npm-shrinkwrap.json or package.json

https://github.com/brainly/style-guide/blob/v44.0.1/package.json
https://github.com/brainly/style-guide/blob/v44.0.1/npm-shrinkwrap.json

**Comment by JamieMason** [comment]
I'm on a train now but that looks like the npm issue in #45, can you verify you're definitely on 3.10.4?

**Comment by aju** [comment]
I installed it today using `sudo npm install -g npm@3.10.4` previously I was on `3.8.7` and it was not working as well. In my shripkwrap file i have paths like `./` shouldn't it be like `file:` ??

**Comment by JamieMason** [comment]
Can you try: npm cache clear, delete shrinkwrap JSON, run shrinkwrap, run shrinkpack?

**Comment by aju** [comment]
I did try it as well :( - please try running `npm i git+https://github.com/brainly/style-guide.git#v44.0.1` in empty folder.

**Comment by JamieMason** [comment]
Damn, sorry about this. I am away until the weekend but will look into it and arrange a fix once I'm back.

**Comment by aju** [comment]
Thank you for fast replay :)

**Comment by brutuscat** [comment]
~~I got this fixed using npm npm >= 3.10.4~~

**Comment by aju** [comment]
@brutuscat are you able to run `npm i git+https://github.com/brainly/style-guide.git#v44.0.1` ??

**Comment by brutuscat** [comment]
@aju no sorry, I was referring to the issue of `npm ERR! addLocal Could not install` when running  npm install from a shrinkpack-ed repo... #41. I'll make my comment invalid to avoid confusion.

**Comment by Arkotek** [comment]
Same here, I cannot install a shrinkpacked module, globally and locally, I always get thesed errors:

```
npm ERR! addLocal Could not install /root/.nvm/versions/node/v4.4.4/lib/node_modules/sample-scrap/node_shrinkwrap/xtend-4.0.1.tgz
[...]
npm ERR! enoent ENOENT: no such file or directory, open '/root/.nvm/versions/node/v4.4.4/lib/node_modules/sample-scrap/node_shrinkwrap/ansi-regex-2.0.0.tgz'
```

Versions:

```
root@master: ~
>>> node -v
v4.4.4

root@master: ~
>>> npm -v
3.10.5

root@master: ~
>>> shrinkpack --version
0.13.1
```

**Comment by JamieMason** [comment]
@aju (/cc @Arkotek)

I just ran the following and everything worked;

```
git clone https://github.com/brainly/style-guide.git
cd style-guide/
npm i
npm shrinkwrap --dev
shrinkpack
rm -rf node_modules/
npm i
```

However, I think I know what the problem is **`npm install some-shrinkpacked-package` will not work**. I realise now from your https://github.com/JamieMason/shrinkpack/issues/56#issuecomment-231029833 that this is what you were trying to do.

This is the fault of unclear documentation on my part (which I will improve) but in summary.
- If you are working on a project which is the root of the tree of dependencies, use shrinkpack.
- If you are working on a project which is itself an npm dependency of other projects, do not use shrinkpack – let downstream projects manage their own bundling.

Shrinkpack is not intended for use in packages published to the registry;
- It's purpose is to add resilience against the registry being unavailable, so to do it within packages which are themselves hosted _on that registry_ would not help.
- The size of packages would grow if 1000s of them all bundled their dependencies, many of which would likely be duplicated.

Please let me know of any questions/concerns, or if anything is not clear, so I can take it into account when explaining this in the docs.

Thanks all.

**Comment by aju** [comment]
Hi
Thanks for the information. Do you have any future plans to make it work for dependent packages ?

**Comment by aju** [comment]
BTW when I added just npm-shrinkpack.json to style guide repo it did't work as well when used with root project that was using shrinkpack :(

**Comment by JamieMason** [comment]
> Thanks for the information. Do you have any future plans to make it work for dependent packages?

For the reasons in https://github.com/JamieMason/shrinkpack/issues/56#issuecomment-231663704 I don't think it's right that packages published to the registry bundle their dependencies in this way.

> BTW when I added just npm-shrinkpack.json to style guide repo it did't work as well when used with root project that was using shrinkpack :(

You'll also need the `node_shrinkwrap/*.tgz` and be sure that `npm-shrinkwrap.json` and everything else is up to date with your latest dependency graph. Your style-guide project should work as I ran it earlier this morning.
